### ISSUE TITLE
Joiplay maybe? 

### ISSUE THREAD

**Issue by Verygood018** [Sawapine/LonaRPG_Booba#1]
Having this joiplay error every time long looses. It just cut off the fun part! 
![Screenshot_2024-02-29-18-52-21-927_cyou joiplay rpgm](https://github.com/Sawapine/LonaRPG_Booba/assets/161883213/98c62afe-e6e2-4de5-9a87-58e0fb230c66)
![Screenshot_2024-02-29-19-05-07-314_cyou joiplay rpgm](https://github.com/Sawapine/LonaRPG_Booba/assets/161883213/0f4c92f2-c7d0-4293-ba43-d060d955a372)

**Comment by Sawapine** [comment]
> Having this joiplay error every time long looses. It just cut off the fun part! 

Make sure you don't have things like `AddExpandedBooba` and `AidExpandedBooba` in your inventory. When enemies grab Lona or when you discard these items, this error occurs. I left it untouched to show that if you want to remove this mod, you will have to **remove** these things from your inventory, however throwing them out of your inventory is the wrong way to get rid of these things, as loading a save with the mod turned off will corrupt that save.

I recommend using the [Cheat Menu Framework](https://github.com/K3nny567/Cheat-Menu-Framework) to remove these items.

**Comment by Verygood018** [comment]
Sorry, this didn't work. I don't have any of this in my inventory, and even so, the error pops out. I'm sure, that don't have any mods, that will crash the game, it's only lona booba, cheats mod, umm and skip adult content warning. With what this error could related?

**Comment by Verygood018** [comment]
Turns out, save was dead

**Comment by Sawapine** [comment]
Fixed in 2.7
